### ISSUE TITLE
IndexOutOfBoundsException happening inside the SDK 

### ISSUE THREAD

**Issue by LouisLin0706** [qualaroo/AndroidSDK#15]
> 2020-05-06 17:23:38.693 28679-28679/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.qualaroo.showcase, PID: 28679
>     java.lang.IndexOutOfBoundsException: Index: 8, Size: 0
>         at java.util.ArrayList.get(ArrayList.java:437)
>         at com.qualaroo.ui.render.f$1.a(Unknown Source:12)
>         at com.qualaroo.a.c.onClick(Unknown Source:16)
>         at android.view.View.performClick(View.java:6603)
>         at android.view.View.performClickInternal(View.java:6576)
>         at android.view.View.access$3100(View.java:780)
>         at android.view.View$PerformClick.run(View.java:26088)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6703)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 

Both production & official showcase app are using the same key. They are facing the same crash

**Comment by durgeshqualaroo** [comment]
@LouisLin0706 We sincerely sorry for the inconvenience. We had an infrastructural issue within our REST API server that we have handled completely. Please connect with us at mobile@qualaroo.com if you're still experiencing the same problem.
