### ISSUE TITLE
Adding Qualaroo library is overriding some styling colors

### ISSUE THREAD

**Issue by ahabbaba9** [qualaroo/AndroidSDK#17]
My app is using the BottomNavigationView component from Google and has a given color scheme set up already.
When I add the Qualaroo library to the project, the bottom nav color style is getting overridden. See screenshots for the experience. I'm unaware of other areas being affected. No other changes have been made, besides adding the SDK in `build.gradle`.

Without Qualaroo library:
![Screen Shot 2020-10-08 at 12 40 49 PM](https://user-images.githubusercontent.com/8433292/95509915-029da000-096a-11eb-8504-39f1e208ec91.png)

With Qualaroo:
![Screen Shot 2020-10-08 at 9 24 59 AM](https://user-images.githubusercontent.com/8433292/95509974-1812ca00-096a-11eb-8b87-c6a50c32bc41.png)

Please fix this!

**Comment by durgeshqualaroo** [comment]
The CSS conflict was handled in v2.0.0. Thanks for the valuable suggestions.
