### ISSUE TITLE
App crash when using Qualaroo SDK 1.4.1

### ISSUE THREAD

**Issue by chapp-hk** [qualaroo/AndroidSDK#3]
Please see the logcat below

> 
> FATAL EXCEPTION: main
> Process: my.app, PID: 7264
> java.lang.NoSuchFieldError: No static field qualaroo__survey_empty_space of type I in class Lcom/qualaroo/R$id; or its superclasses (declaration of 'com.qualaroo.R$id' appears in /data/app/my.app/base.apk:classes16.dex)
> at com.qualaroo.ui.e.onViewCreated(Unknown Source)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
> at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
> at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
> at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
> at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
> at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
> at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
> at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
> at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
> at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
> at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
> at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
> at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
> at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
> at android.app.Activity.performStart(Activity.java:6915)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
> at android.app.ActivityThread.access$1100(ActivityThread.java:221)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:158)
> at android.app.ActivityThread.main(ActivityThread.java:7225)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
>

**Comment by scana** [comment]
Hey @chapp-hk, thank you for your report.

I am not able to reproduce this issue right now. It's weird as 1.4.1 does not use `qualaroo__survey_empty_space` field anymore.

Please help me out with answering some of the questions below:
- Did you update from 1.0.0? Is there any module in you project that still depends on 1.0.0?
- This is from your local project, right (it's not a crash from Google Play)? Did you try cleaning and rebuilding it? Does it help?
- Is there any chance that you have any kind of resource (layouts/strings/dimens etc) declared with a name starting with a `qualaroo__` prefix?
- Are you using `com.android.support:appcompat-v7` library? Which version?
- Are you using `com.android.support:design` library? Which version?

Errors similar to yours might happen when there are multiple resources with the same resource identifier found in a project (it doesn't even have to be a Qualaroo`s resource, as far as I know) and there is a naming clash.

**Comment by scana** [comment]
Issue was solved by cleaning and rebuilding the project.
