### ISSUE TITLE
setUserId() and setUserProperty() not work

### ISSUE THREAD

**Issue by chapp-hk** [qualaroo/AndroidSDK#7]
Qualaroo sdk initialized in Application class.

All the user id, keys and values are not null/empty

After calling setUserId() and setUserProperty(), "properties" is empty when checking in REST Reporting API.

Qualaroo sdk version: 1.4.4

**Comment by scana** [comment]
Hey @chapp-hk - this issue has been resolved in our recent release. Please update to 1.5.0.
