### ISSUE TITLE
Survey not showing in release build with pro-guard enabled

### ISSUE THREAD

**Issue by sumit007** [qualaroo/AndroidSDK#8]
Surveys are visible in debug build but not in release build with pro-guard enabled. What will be the pro-guard rules for SDK.

**Comment by scana** [comment]
Hey @sumit007, thank you for your report.
Would you mind telling me which version of the SDK are you using? And also, are you using regular ProGuard or R8?

Our SDK comes with pre-bundled ProGuard rules and there should be no need for you to set them. 
I'll try to reproduce the issue though, as soon as I find out which version are you using.

**EDIT:**
Also, could you please turn on debug mode for QualarooSdk (https://github.com/qualaroo/AndroidSDK#debugging) and see what kind of logs are you getting when trying to display a survey on release builds?

**EDIT2:**
I tried to reproduce your issue on few recent versions, but I was not able to do that.
If you don't mind that, you could share your current ProGuard configuration (proguard file + relevant part of build.gradle file) with me to marcin@qualaroo.com. Maybe I could be of help this way?
Also, a release version of the APK would work.

**Comment by sumit007** [comment]
Hey @scana I am using SDK version 1.6.3, We are using Regular Proguard.

**Comment by scana** [comment]
Hey @sumit007, I decompiled an APK that you have provided.
It seems that our internal model files got obfuscated for some weird reason (which is of course the reason our SDK is not working for you).

Could you please try adding this rule and try again?
```
-keep public class com.qualaroo.internal.model.** {
    private *;
    <init>(...);
}
```

I apologize for the inconvenience. I will make sure that this issue will be resolved in the next release.

**Comment by sumit007** [comment]
Hey @scana, with the pro-guard rules provided, We are not the getting the surveys so we kept all the SDK files as mentioned below

`-keep public class com.qualaroo.** { *; }
`

and it worked. Thank you for the your help.
