### ISSUE TITLE
Qualaroo SDK 1.8.1 crashes in Android 9

### ISSUE THREAD

**Issue by chapp-hk** [qualaroo/AndroidSDK#9]
Hi Qualaroo team,

We found crash reports on Firebase Crashlytics about Qualaroo SDK
All the crashes come from Android 9
**Android targetSdk: 28**
**Qualaroo SDK version: 1.8.1**

> Fatal Exception: java.lang.NoClassDefFoundError
> Failed resolution of: Lorg/apache/commons/logging/LogFactory;
> 
> org.apache.commons.jexl3.internal.Engine$UberspectHolder. (Engine.java:69)
> org.apache.commons.jexl3.internal.Engine$UberspectHolder.access$000 (Engine.java:67)
> org.apache.commons.jexl3.internal.Engine.getUberspect (Engine.java:187)
> org.apache.commons.jexl3.internal.Engine. (Engine.java:149)
> org.apache.commons.jexl3.JexlBuilder.create (JexlBuilder.java:388)
> com.qualaroo.internal.r. (Unknown Source:10)
> com.qualaroo.Qualaroo$Builder.createInstance (Unknown Source:200)
> com.qualaroo.Qualaroo$Builder.init (Unknown Source:7)
> our.company.App.initLocalizedSDKs (App.java:166)

**Comment by scana** [comment]
Hey @chapp-hk thank you for your report.

Please, update your qualaroo-sdk version to `1.8.2`.
We removed the dependency of `commons-logging` library, this should resolve the issue for Android Pie devices.

Please, feel free to reopen the issue if anything comes up.
